'--------------------------------------
SDA				CON	P8
SCL				CON	P9
EEPROM_ID		CON	%10100001
RTC_ID    		CON %11010000
VALOR_DIGITAL	VAR	BYTE
VALOR_DIGITAL2	VAR	BYTE(20)
VALOR_VOLTIOS	VAR	LONG(20)
TEMPERATURA		VAR	LONG(20)
RELOJ_ADC		CON	2
TIEMPO			VAR WORD
TIEMPO2			VAR WORD
CONTEO			VAR NIB
CONTEO2			VAR NIB
MUESTRASTOTAL	VAR BYTE
MUESTRA			VAR	BYTE
CONTI			VAR	BIT
PAX3			VAR BIT
PAX2			VAR	BIT
PAX1			VAR	BIT
PAX0			VAR BIT
RTC             VAR Byte (7)
Seg      		CON  0         'Pos. dentro del arreglo RTC de los segundos
Min      		CON  1         'Pos. dentro del arreglo RTC de los minutos
Hora     		CON  2         'Pos. dentro del arreglo RTC de las horas
Dia      		CON  4         'Pos. dentro del arreglo RTC del día del mes
Mes      		CON  5         'Pos. dentro del arreglo RTC del mes
Ano      		CON  6         'Pos. dentro del arreglo RTC del año
MATAR			VAR BIT
INDEX			VAR NIB
'----------------------------------------
'GOSUB	INICIAR_LCD
PAUSE 1000               'Espera opcional 
GOSUB IniciarDS1307      'Inicializa al Reloj de tiempo real

RTC (Seg)  = $0          'Ajusta los segundos iniciales
RTC (Min)  = $30         'Ajusta los minutos iniciales
RTC (Hora) = $8          'Ajusta la  hora inicial
RTC (Dia)  = $5          'Ajusta el  día inicial
RTC (Mes)  = $7          'Ajusta el  mes inicial
RTC (Ano)  = $5          'Ajusta el  año inicial

I2COUT SDA,SCL,RTC_ID,0,[STR RTC\7]  'Envía los ajustes iniciales desde el           
                                       'microcontrolador hasta el reloj 1307
PAUSE 1000               'Espera opcional
'----------------------------------------
PRINCIPAL:
		CONTI=0
		TIEMPO=1000
		MUESTRASTOTAL=10
		CONTEO=0
		CONTEO2=0
		MATAR=0
		DO
		GOSUB SELECCION
		WHILE(CONTI=1)
END
'----------------------------------------
IniciarDS1307:
		HIGH SDA
  		HIGH SCL
  		PAUSE 100        'Garantizar la condición de "bus free" para los disp. I2C
  		I2CIN  SDA,SCL,RTC_ID,0,[RTC (Seg)]       
  		I2COUT SDA,SCL,RTC_ID,0,[RTC (Seg)& $7F] 
  		'Aquí se activa el oscilador del DS1307 sin perder su configuración previa
RETURN

INICIAR_LCD:
		PAUSE 1000
		LCDWRITE P1\P3\P2, OUTB,[INITLCD1,INITLCD2,TWOLINE]
		PAUSE 100
		LCDWRITE P1\P3\P2, OUTB,[INITLCD1,INITLCD2,TWOLINE,CLEAR,HOME,SCR]
RETURN

SELECCION:
		REPEAT
		PAUSE 500
		SEROUT S_OUT,I9600,[0]
	    SEROUT S_OUT,I9600,[10,13,"1. CAMBIAR HORA"]
		SEROUT S_OUT,I9600,[10,13,"2. MEDIR TEMP"]
		SEROUT S_OUT,I9600,[10,13,"3. LEER EEPROM"]
		GOSUB LEER_HORA
		SEROUT S_OUT,I9600,[10,13," HORA  = ",DEC RTC(Hora),":",DEC RTC(Min),":",DEC RTC(Seg),13]
        SEROUT S_OUT,I9600,[" FECHA = ",DEC RTC(Dia),"/",DEC RTC(Mes),"/",DEC RTC(Ano)]
			PAX3=INAX3
			PAX2=INAX2
			PAX1=INAX1
		UNTIL ((PAX3=1) OR (PAX2=1) OR (PAX1=1))
		IF PAX3=1 THEN
			GOSUB CAMBIARHORA
		ENDIF
		IF PAX2=1 THEN
			GOSUB MEDIRTEMP
		ENDIF
		IF PAX1=1 THEN
			GOSUB LEEREEPROMENVIAR
		ENDIF
	
RETURN

CAMBIARHORA:
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["HORA: ",DEC RTC(HORA)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(HORA)=RTC(HORA)+$1
		ENDIF
		IF RTC(HORA)=$18 THEN
		RTC(HORA)=$1
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)
		PAUSE 500
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["MIN: ",DEC RTC(MIN)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(MIN)=RTC(MIN)+$1
		ENDIF
		IF RTC(MIN)=$3C THEN
		RTC(MIN)=$0
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)	
		PAUSE 500
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["SEG: ",DEC RTC(SEG)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(SEG)=RTC(SEG)+$1
		ENDIF
		IF RTC(SEG)=$3C THEN
		RTC(SEG)=0
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)	
		PAUSE 500
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["DIA: ",DEC RTC(DIA)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(DIA)=RTC(DIA)+$1
		ENDIF
		IF RTC(DIA)=$20 THEN
		RTC(DIA)=1
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)	
		PAUSE 500
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["MES: ",DEC RTC(MES)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(MES)=RTC(MES)+$1
		ENDIF
		IF RTC(MES)=$C THEN
		RTC(MES)=0
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)	
		PAUSE 500
		DO
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["ANO: ",DEC RTC(ANO)]
		PAUSE 100
		IF INAX2=1 THEN
		RTC(ANO)=RTC(ANO)+$1
		ENDIF
		IF RTC(ANO)=$A THEN
		RTC(ANO)=$0
		PAUSE 500
		ENDIF
		WHILE (INAX1=0)	
'		GOSUB IniciarDS1307      'Inicializa al Reloj de tiempo real
		I2COUT SDA,SCL,RTC_ID,0,[STR RTC\7]
		PAUSE 1000
		CONTI=1
		
RETURN
		
MEDIRTEMP:
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["COLOQUE TIEMPO"]	
		DO
			SEROUT S_OUT,I9600,[0]
			IF TIEMPO<1000 THEN
			SEROUT S_OUT,I9600,["TIEMPO: ",DEC TIEMPO," ms"]
			ENDIF
			IF TIEMPO>=1000 THEN
			SEROUT S_OUT,I9600,["TIEMPO: ",DEC TIEMPO/1000," s"]
			ENDIF
			IF INAX2=1 THEN
				CONTEO=CONTEO+1
				IF CONTEO=1 THEN
				TIEMPO=2000
				CONTEO=CONTEO+1
				ENDIF
				IF CONTEO=3 THEN
				TIEMPO=5000
				CONTEO=CONTEO+1
				ENDIF
				IF CONTEO=5 THEN
				TIEMPO=10000
				CONTEO=CONTEO+1
				ENDIF
				IF CONTEO=7 THEN
				TIEMPO=100
				CONTEO=CONTEO+1
				ENDIF
				IF CONTEO=9 THEN
				TIEMPO=500
				CONTEO=CONTEO+1
				ENDIF
				IF CONTEO=11 THEN
				TIEMPO=1000
				CONTEO=0
				ENDIF
				PAUSE 500
			ENDIF
		WHILE(INAX1=0)
		PAUSE 500
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["COLOQUE MUESTRAS"]	
		DO
			SEROUT S_OUT,I9600,[0]
			SEROUT S_OUT,I9600,["MUESTRAS: ",DEC MUESTRASTOTAL]
			IF INAX2=1 THEN
				CONTEO2=CONTEO2+1
				IF CONTEO2=1 THEN
				MUESTRASTOTAL=20
				CONTEO2=CONTEO2+1
				ENDIF
				IF CONTEO2=3 THEN
				MUESTRASTOTAL=50
				CONTEO2=CONTEO2+1
				ENDIF
				IF CONTEO2=5 THEN
				MUESTRASTOTAL=100
				CONTEO2=CONTEO2+1
				ENDIF
				IF CONTEO2=7 THEN
				MUESTRASTOTAL=10
				CONTEO2=CONTEO2+1
				ENDIF		
				PAUSE 500
			ENDIF
		WHILE(INAX1=0)
		I2COUT	SDA,SCL,EEPROM_ID,0,[RTC(HORA)]
		I2COUT	SDA,SCL,EEPROM_ID,1,[RTC(MIN)]
		I2COUT	SDA,SCL,EEPROM_ID,2,[RTC(SEG)]
		I2COUT	SDA,SCL,EEPROM_ID,3,[RTC(DIA)]
		I2COUT	SDA,SCL,EEPROM_ID,4,[RTC(MES)]
		I2COUT	SDA,SCL,EEPROM_ID,5,[RTC(ANO)]
		FOR MUESTRA = 6 TO MUESTRASTOTAL+5 
			SEROUT S_OUT,I9600,[0]
			SEROUT S_OUT,I9600,["MIDIENDO TEMP."]
			GOSUB LEER_HORA
			ADIN AX0,RELOJ_ADC,AD_RON,VALOR_DIGITAL
			I2COUT	SDA,SCL,EEPROM_ID,MUESTRA,[VALOR_DIGITAL]
			PAUSE TIEMPO
		NEXT
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["MED. EXITOSA"]
     	SEROUT S_OUT,I9600,[10,13,"PRESIONE S1"]
		DO
		WHILE(INAX1=0)
		CONTI=1
		PAUSE 500
RETURN

Leer_Hora:
  I2CIN  SDA,SCL,RTC_ID,0,[STR RTC\7]    'Lectura de los 7 bytes de información
  GOSUB BCD2BIN                          'Llevar a binario para trabajar 
RETURN

'Rutina para convertir un arreglo de números BCD a Binario
BCD2BIN:
  FOR Index = 0 TO 6
    RTC(Index) = (RTC(Index)/16)*10 + RTC(Index).NIB0
  NEXT
RETURN

LEEREEPROMENVIAR:
        I2CIN	SDA,SCL,EEPROM_ID,0,[RTC(HORA)]
		I2CIN	SDA,SCL,EEPROM_ID,1,[RTC(MIN)]
		I2CIN	SDA,SCL,EEPROM_ID,2,[RTC(SEG)]
		I2CIN	SDA,SCL,EEPROM_ID,3,[RTC(DIA)]
		I2CIN	SDA,SCL,EEPROM_ID,4,[RTC(MES)]
		I2CIN	SDA,SCL,EEPROM_ID,5,[RTC(ANO)]
		FOR MUESTRA=6 TO MUESTRASTOTAL+5 
			I2CIN	SDA,SCL,EEPROM_ID,MUESTRA-6,[VALOR_DIGITAL2(MUESTRA-6)]
			VALOR_VOLTIOS(MUESTRA-6) = (FLOAT(VALOR_DIGITAL2(MUESTRA-6)) FMUL 5.0) FDIV 1024.0
			TEMPERATURA(MUESTRA-6) = VALOR_VOLTIOS(MUESTRA-6) FMUL 100.0
		NEXT
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["DATOS OBTENIDOS"]		
		SEROUT S_OUT,I9600,[10,13,"PRESIONE S1"]
		DO
		WHILE(INAX1=0)
		SEROUT S_OUT,I9600,[10,13," HORA  = ",DEC RTC(Hora),":",DEC RTC(Min),":",DEC RTC(Seg),13]
        SEROUT S_OUT,I9600,[" FECHA = ",DEC RTC(Dia),"/",DEC RTC(Mes),"/",DEC RTC(Ano)]
		FOR MUESTRA = 0 TO MUESTRASTOTAL-1 
			SEROUT S_OUT,I9600,[10,13,"T",DEC MUESTRA+1,"= ",REAL TEMPERATURA(MUESTRA)\2," oC"]
		NEXT
		SEROUT S_OUT,I9600,[10,13,"PRESIONE S1"]
		DO
		WHILE(INAX1=0)
		CONTI=1
		PAUSE 500
RETURN

FINAL:
		SEROUT S_OUT,I9600,[0]
		SEROUT S_OUT,I9600,["HASTA LUEGO"]
		CONTI=0
RETURN
		
		
